### ISSUE TITLE
Point/time mismatch

### ISSUE THREAD

**Issue by bnordlund** [dwilhelm89/LeafletSlider#20]
Firstly, thank you for your work at making this handy control. There appears, however, to be a mismatch between what point appears and at which time it appears. Specifically, in your example the second point (at 7.602516645, 51.94962073) appears at time 10:03:29 (which corresponds to the third point in points.json) and at the fourth position on the slider. Simply adjusting offsets in the startSlider portion of SliderControl.js felt kludge...do you think there's a better fix?

**Comment by juliensoret** [comment]
About the mismatch of Point and Time, it seems to be caused by the example not using the last version of the plugin. In which it works. This pull https://github.com/dwilhelm89/LeafletSlider/pull/24 should correct the example.
About the mismatch Point / Slider position, this is something I will try to work on. Maybe dwilhelm89 has some hints?
